name: OpenID Connect
on: push
env:
    ROLE_ARN: arn:aws:iam::${{ secrets.AWS_ID }}:role/${{ secrets.ROLE_NAME}}
    SESSION_NAME: gh-oidc-${{ github.run_id}}-${{github.run_attempt}}

defaults:
    run:
        shell: bash    

jobs:
    oidc:
        permissions:
            id-token: write
        timeout-minutes: 5
        runs-on: ubuntu-22.04
        steps:
            - uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-region: ap-northeast-1
                role-to-assume: ${{env.ROLE_ARN}}
                role-session-name: ${{env.SESSION_NAME}}
            - run: aws iam list-users
            - run: aws iam create-user --user-name invalid || true
            - run: echo ${{secrets.AWS_ID}} >> test.txt
            - name: Archive code coverage results
              uses: actions/upload-artifact@v4
              with:
                name: test
                path: test.txt